### PR TITLE
Fix spawning of Node.js binaries (.cmd files) on Windows

### LINKED ISSUE #5: Running any yarn script in multiview doesn't work
I'm trying to use multiview with yarn and I want to have this in my `"scripts"` section of `package.json`:

```js
"dev": "yarn build:dev && multiview [yarn watch] [yarn run:api] [yarn run:server]"
```

But after the `build:dev` scripts finishes (just runs webpack with dev config) multiview starts and displays `<command> (done)` and `Exited with code 1` for each command without ever running them.

I have confirmed that this is not due to webpack or nodemon (which are used in my watch and run:* tasks) by having this in my `"scripts"` section:

```js
"testmv1": "multiview [yarn lsla]",
"testmv2": "multiview [ls -la]",
"lsla": "ls -la"
```

Running `yarn testmv1` shows same behavior as my config (i.e. the `lsla` script is not executed by multiview and it reports exit code 1) while running `yarn testmv2` executes `ls -la` and displays its output correctly.

I have tested this on Windows 10 (x64, latest insider fast build) with Node v7.8.0 and Yarn v0.22.0 (which is current RC, tried first with latest stable v0.21.3 but it's the same behavior with both versions).

### PR DESCRIPTION
**Pull request by raleksandar**
This PR fixes running .bat/.cmd files on Windows (and .cmd files are used to wrap Node.js binaries installed via npm and yarn) by setting `shell` options of `child_process.spawn()` call on WIndows only.

Fixes #5

### CODE REVIEW

File: lib/Spawn.js [hunk 1]
```diff
@@ -3,7 +3,16 @@ var spawn = require('child_process').spawn;
 function Spawn(stream, command, args, name, output) {
   var exited = false;
   var ended = false;
-  var spawnedProcess = spawn(command, args);
```
Comment (arjunmehta) [inline lib/Spawn.js]: Please keep `spawnedProcess` initialized at the top of the method here (keep undefined):
```javascript
var spawnedProcess;
```

File: lib/Spawn.js [hunk 2]
```diff
@@ -3,7 +3,16 @@ var spawn = require('child_process').spawn;
...
+  var options;
+
+  if (process.platform === 'win32') {
+    options = {
+      // required so that .bat/.cmd files can be spawned
+      shell: process.env.comspec || 'cmd.exe',
+    };
+  }
+
+  var spawnedProcess = spawn(command, args, options);
```
Comment (arjunmehta) [inline lib/Spawn.js]: Keeping with above comment remove `var`:
```
spawnedProcess = spawn(command, args, options);
```

File: lib/Spawn.js [hunk 3]
```diff
@@ -3,7 +3,16 @@ var spawn = require('child_process').spawn;
 function Spawn(stream, command, args, name, output) {
   var exited = false;
   var ended = false;
-  var spawnedProcess = spawn(command, args);
+  var options;
+
+  if (process.platform === 'win32') {
+    options = {
+      // required so that .bat/.cmd files can be spawned
+      shell: process.env.comspec || 'cmd.exe',
```
Comment (arjunmehta) [inline lib/Spawn.js]: remove trailing comma

**Comment by raleksandar** [comment]
Made requested changes. Do you want me to rebase and squash these in a single commit?

**Comment by arjunmehta** [comment]
Looks good!
I would like to find a way to test on a CI that supports windows. I've been wanting to do this for a while.
That way we can ensure that it works on all versions of node (1-7) on all platforms.

For now let's merge and I'll find a way of testing before publishing a new release.

Thank you for your help!

**Comment by raleksandar** [comment]
Happy to help :)
